### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by nutellazpw** [niekcandaele/CSGO-RankMe-stats#12]
Hello,
how i can install this on my webserver. Is it possible?
I need only Web page , not discord stats!
Thanks !

**Comment by niekcandaele** [comment]
Have you had a look at [the installation guide](https://github.com/niekcandaele/CSGO-RankMe-stats/wiki/Installation)?

Are you having an issue with a specific step?

**Comment by nutellazpw** [comment]
I don't have SSH acess on web hosting, and can t launch commands from installation ...

**Comment by niekcandaele** [comment]
Then sadly it will not work. This is a nodejs app, not php. 

Consider using the free credits via referral linked in the install guide if you want to try it out. 😃
