### ISSUE TITLE
Fresh install, get error

### ISSUE THREAD

**Issue by ezspot** [niekcandaele/CSGO-RankMe-stats#15]
- **Environment**:
Windows/Linux ? Distro?
ubuntu 18.04

- **Description**:
root@**:~# docker run --env-file ~/.env catalysm/csgo-rankme:latest
Unable to find image 'catalysm/csgo-rankme:latest' locally
latest: Pulling from catalysm/csgo-rankme
c5e155d5a1d1: Pull complete 
221d80d00ae9: Pull complete 
4250b3117dca: Pull complete 
3b7ca19181b2: Pull complete 
425d7b2a5bcc: Pull complete 
69df12c70287: Pull complete 
2a68245de447: Pull complete 
4f61e9705839: Pull complete 
1a9e85971619: Pull complete 
8030d343a615: Pull complete 
ccf933e8fa43: Pull complete 
93794d3334ad: Pull complete 
Digest: sha256:93fb476795e68a83eb1ea871f25a3356d5c085e8aeee71fac566e07dc660025b
Status: Downloaded newer image for catalysm/csgo-rankme:latest

> rankme-stats@1.2.5 start /usr/src/app
> node src/index.js

info: Detected 1 available CPUs, scaling webserver to 1 processes
info: Unhandled Rejection at: Promise
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rankme-stats@1.2.5 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rankme-stats@1.2.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-04T23_12_51_111Z-debug.log
root@**:~# more /root/.npm/_logs/2019-06-04T23_12_51_111Z-debug.log
more: stat of /root/.npm/_logs/2019-06-04T23_12_51_111Z-debug.log failed: No such file or directory

**Comment by niekcandaele** [comment]
Could you show me the contents of the .env file please (make sure to redact/change) any sensitive info? I suspect there's a misconfiguration there and the app is not reporting it correctly 

`info: Unhandled Rejection at: Promise` is the (very helpful :)) log line

**Comment by ezspot** [comment]
.env contains:
MYSQL_DB=games
MYSQL_TABLE=**
MYSQL_HOST=IP
MYSQL_PASSWORD=**
MYSQL_USER=**

**Comment by ezspot** [comment]
I assume DISCORD_TOKEN is not a req. variable? So i just updated it with my mysql info.
Just nano .env and entered the detailes in root.

**Comment by ezspot** [comment]
Seems like it is req?

Got this now:

`root@**:~# docker run --env-file ~/.env catalysm/csgo-rankme:latest

> rankme-stats@1.2.5 start /usr/src/app
> node src/index.js

info: Detected 1 available CPUs, scaling webserver to 1 processes
  ____             _    __  __            _        _       
 |  _ \ __ _ _ __ | | _|  \/  | ___   ___| |_ __ _| |_ ___ 
 | |_) / _` | '_ \| |/ / |\/| |/ _ \ / __| __/ _` | __/ __|
 |  _ < (_| | | | |   <| |  | |  __/ \__ \ || (_| | |_\__ \
 |_| \_\__,_|_| |_|_|\_\_|  |_|\___| |___/\__\__,_|\__|___/
                                                           
info: Unhandled Rejection at: Promise
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rankme-stats@1.2.5 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rankme-stats@1.2.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-04T23_35_24_749Z-debug.log
root@**:~# `

**Comment by ezspot** [comment]
Anyway to fix it manually easy? Should it not just need my DB-info to connect to and we are good to go?

**Comment by ezspot** [comment]
@niekcandaele

**Comment by niekcandaele** [comment]
Please don't spam like that, I'll get to your issue when I have time. 

EDIT: btw, you can just disable the discord bot in config.json

**Comment by ezspot** [comment]
Seems like i fixed it.
