### ISSUE TITLE
Unable to start Docker container post-CI update

### ISSUE THREAD

**Issue by grahams** [niekcandaele/CSGO-RankMe-stats#23]
**Describe the bug**
The `sequelize` update bundled into the CI fix seems to have broken db connections (perhaps just on Docker).  [I believe it is this change to index.js](https://github.com/niekcandaele/CSGO-RankMe-stats/pull/21/files#diff-1fdf421c05c1140f6d71444ea2b27638)

Not sure if it's the interpolation failing or if the env members are not correctly populated.

**To Reproduce**
1. Launch the app in a docker container 

**Expected behavior**
The application launches

**Screenshots**
```
info: Detected 6 available CPUs, scaling webserver to 6 processes

[...]

error: Fatal error while connecting to database SequelizeConnectionError: Access denied for user 'sourcemod'@'%' to database ':undefined/sourcemod'
```

**Environment info:**
 - OS: macOS (Docker)
 - CSGO stats version: master

**Comment by niekcandaele** [comment]
Ah crap, my bad.

https://github.com/niekcandaele/CSGO-RankMe-stats/blob/master/src/index.js#L89

Doesn't handle default port properly. Add a env var `MYSQL_PORT` and that should make it work again
