### ISSUE TITLE
Unknown database ':undefined/rankme'

### ISSUE THREAD

**Issue by KillerRoi** [niekcandaele/CSGO-RankMe-stats#28]
**Description**
info: Detected 2 available CPUs, scaling webserver to 2 processes
error: Fatal error while connecting to database SequelizeConnectionError: Unknown database ':undefined/rankme'
ubuntu@ip:~/CSGO-RankMe-stats-master$ node src/index.js
info: Detected 2 available CPUs, scaling webserver to 2 processes
error: Fatal error while connecting to database SequelizeConnectionError: Unknown database ':undefined/rankme'

**To Reproduce**
1. Go to 'master/src'
2. Start 'node index.js'

**Expected behavior**
The Bot Working With The Database Specified in The .env Config!

**Screenshots**
![image](https://user-images.githubusercontent.com/54289708/87846056-9c652c00-c8ea-11ea-9bc7-4dee16e3702f.png)

**Environment info:**
 - OS: Ubuntu 18.04
 - CSGO stats version: Latest
 - Node version: v10.21.0
 - Browser: Firefox

**Additional context**

**Comment by niekcandaele** [comment]
Hi, try adding the MYSQL_PORT variable to your env

https://github.com/niekcandaele/CSGO-RankMe-stats/blob/cf1c7326c3b1d770cc3c05cd1a01e802641b00dd/src/index.js#L89
