### ISSUE TITLE
Configure linebreak between player name & stat number in stats command

### ISSUE THREAD

**Issue by Summer-16** [niekcandaele/CSGO-RankMe-stats#3]
For the !Stats message - I want the player's name and his points in same line. Right now the points/kills goes in 2nd line which makes message too lengthy in mobile view  but i would like them to be in same line as !top has.
How can i do that?

**Comment by niekcandaele** [comment]
Answered on discord:

```
10:05 AM] ☕ Catalysm 🚀: @Summer_Soldier you can turn off "stats_showMedals" in config.json to condense the message
[10:05 AM] ☕ Catalysm 🚀: I'm happy to take a PR with other formatting options though
```
