### ISSUE TITLE
:/

### ISSUE THREAD

**Issue by NichlasHakon** [niekcandaele/CSGO-RankMe-stats#30]
It keeps giving me these errors on fully new download

![image](https://user-images.githubusercontent.com/70380554/102725898-9270aa80-431a-11eb-9447-1d0d66f686e3.png)

**Comment by niekcandaele** [comment]
Hey, just googled a bit and looks like you are probably missing some system dependencies

https://github.com/nodejs/node-gyp/issues/809#issuecomment-166704390

In your screenshot specifically I see 

![image](https://user-images.githubusercontent.com/22315101/102726196-f8f6c800-431c-11eb-8461-32a987e98c1c.png)


If you install these missing dependencies, it should work as expected

**Comment by NichlasHakon** [comment]
now it gives me these errors after installing python

**Comment by NichlasHakon** [comment]
Now it gives me this 
[errors.txt](https://github.com/niekcandaele/CSGO-RankMe-stats/files/5723435/errors.txt)

**Comment by NichlasHakon** [comment]
now it gives me these errors

Too long for me to take a screenshot 
[errors.txt](https://github.com/niekcandaele/CSGO-RankMe-stats/files/5723470/errors.txt)

**Comment by niekcandaele** [comment]
Did you try the other steps in the issue I linked? This is not really an issue with the CSGO-rankme project, but rather an issue with your installation of node. It is trying to compile native addons and failing, so likely you're missing some build tools.

**Comment by NichlasHakon** [comment]
ye just noticed that it says something about node-pre-gyp not working hence could be why it doesnt work

**Comment by NichlasHakon** [comment]
yes it was Node-pre-gyp
 i got it to work now thanks for fast response time 👍
