### ISSUE TITLE
Web Interface | Doubt with installation process

### ISSUE THREAD

**Issue by crashzk** [niekcandaele/CSGO-RankMe-stats#31]
- **Environment**:
Linux

- **Description**:
I read the installation tutorial for [Wiki](https://github.com/niekcandaele/CSGO-RankMe-stats/wiki/Installation) but from what I saw it is only about installing the BOT Discord.

If I want to install only the Web part, would it be possible? Would you have a tutorial for that?

**Comment by niekcandaele** [comment]
Disable it in the config
https://github.com/niekcandaele/CSGO-RankMe-stats/blob/master/config.json#L6

**Comment by crashzk** [comment]
> Disable it in the config
> https://github.com/niekcandaele/CSGO-RankMe-stats/blob/master/config.json#L6

Ok, I disabled the BOT part, I configured the .env file with the information from the RankME database.

https://veseaprende.com.br/rank3/

Anything I missed, shouldn't it show the web interface already?

**_NOTE: Currently I use a Web Hosting, for this reason I cannot install the BOT._**

**Comment by niekcandaele** [comment]
It's not a PHP app or static web files. It's a nodejs application. I'm afraid you cannot host it like you are trying to. You need a server where you can run the node process

**Comment by crashzk** [comment]
> It's not a PHP app or static web files. It's a nodejs application. I'm afraid you cannot host it like you are trying to. You need a server where you can run the node process

I understand, in any case thank you.
