### ISSUE TITLE
Profile page - Hits radar chart does not display 'head' data

### ISSUE THREAD

**Issue by milanmenezes** [niekcandaele/CSGO-RankMe-stats#7]
The first graph is not reflecting the headshot count

**Comment by niekcandaele** [comment]
Thanks for reporting. I'm quite busy atm. If you want, feel free to make a PR with the fix

**Comment by niekcandaele** [comment]
It seems like the data from the RankMe plugin might be incorrect and 'head' data is much lower than you would expect. 

I've opened an issue in the RankMe repo hoping for some clarification: https://github.com/rogeraabbccdd/Kento-Rankme/issues/106

Is it possible that for you the data **is** displayed but is so small you think it is not? If possible, send me a link to your instance so I can investigate more?

**Comment by niekcandaele** [comment]
@milanmenezes Please try out the new version of RankMe, this issue should be fixed

**Comment by milanmenezes** [comment]
I used the latest release and updated rankme and this fixed the issue. Great work on the historic data btw.
