### ISSUE TITLE
anyway to only use the website?

### ISSUE THREAD

**Issue by LemonPAKA** [niekcandaele/CSGO-RankMe-stats#8]
I want to know could I get a tutorial about how to install it only with web (that discord bot is good but I think I dont need to use it) sorry about my poor english

**Comment by niekcandaele** [comment]
You can disable the bot in config.json

https://github.com/niekcandaele/CSGO-RankMe-stats/blob/e9d10b9b7661e6dab700e9291b295a5dac786e8b/config.json#L4-L10
